# Generated by Django 2.2.2 on 2019-06-16 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('photo_album_api', '0004_photoalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.User')),
                ('photo_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_album_api.PhotoAlbum')),
            ],
        ),
    ]
