# Generated by Django 2.2.2 on 2019-06-16 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='Photos/default/default.jpg', upload_to='Photos/')),
                ('upload_date', models.DateField(default=datetime.date.today)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='page_app.Page')),
            ],
        ),
    ]
